global:
 scrape_interval: 5s
 
scrape_configs:
 - job_name: 'prometheus'
   static_configs:
    - targets: ['127.0.0.1:9090']
   
 - job_name: "my-api-job"
   metrics_path: "/actuator/prometheus"
   static_configs:
    - targets: ['host.docker.internal:8080']
      labels:
       application: "my-api"
